name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  dist:
    name: Make distribution using Dist::Zilla
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache ~/perl5
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-dist-locallib
          path: ~/perl5
      - name: Perl version
        run: |
          perl -v
      - name: Install cpanm
        run: |
          curl -L https://cpanmin.us | perl - --sudo App::cpanminus
      - name: Install local::lib
        run: |
          cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
      - name: Install Dist::Zilla
        shell: bash
        run: |
          eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
          cpanm -n Dist::Zilla
          dzil authordeps --missing | cpanm -n
      - name: Make distribution
        shell: bash
        run: |
          eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
          dzil build --in build-dir
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./build-dir
  test:
    needs: dist
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, windows-latest, ubuntu-latest]
        perl: ['5']
        include:
          - { os: 'ubuntu-latest', perl: "5.14" }
          - { os: 'ubuntu-latest', perl: "5.16" }
          - { os: 'ubuntu-latest', perl: "5.20" }
          - { os: 'ubuntu-latest', perl: "5.30" }
          - { os: 'ubuntu-latest', perl: "5.32" }
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}

    steps:
      - name: Get dist artifact
        uses: actions/download-artifact@v2
        with:
          name: dist

      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        if: matrix.os != 'windows-latest'
        with:
          perl-version: ${{ matrix.perl }}
      - name: Set up perl (Strawberry)
        uses: shogo82148/actions-setup-perl@v1
        if: matrix.os == 'windows-latest'
        with:
          distribution: 'strawberry'

      - name: target-setup-perl (perl -V)
        shell: bash
        run: |
          echo "::group::setup-perl (perl -V)"
          export MYPERL=$(which -a perl | grep -m 1 hostedtoolcache)
          echo "MYPERL=$MYPERL" >> $GITHUB_ENV
          $MYPERL -V
          echo "::endgroup::"

      - name: Install Perl deps
        shell: bash
        run: |
          $MYPERL -S cpanm --notest --installdeps . || ( cat ~/.cpanm/build.log && false )

      - name: Run tests
        shell: bash
        run: |
          $MYPERL -S cpanm --verbose --test-only .
